### ISSUE TITLE
The "github.get_contents" action will fail when decode parameter is set

### ISSUE THREAD

**Issue by userlocalhost** [StackStorm-Exchange/stackstorm-github#41]
When I run following action, it succeed in running this action.
`$ st2 run github.get_contents user=StackStorm repo=st2 path=/LICENSE`

But following action, which adds `decode` parameter, will fail as below.
`$ st2 run github.get_contents user=StackStorm repo=st2 path=/LICENSE decode=True`

Here is a result of running this action with `decode` parameter.
```
ubuntu@localhost:~$ st2 run github.get_contents user=StackStorm repo=st2 path=/LICENSE decode=True
.
id: 60efae5db289e9717c9b1103
action.ref: github.get_contents
context.user: st2admin
parameters: 
  decode: true
  path: /LICENSE
  repo: st2
  user: StackStorm
status: failed
start_timestamp: Thu, 15 Jul 2021 03:41:17 UTC
end_timestamp: Thu, 15 Jul 2021 03:41:18 UTC
result: 
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 395, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 214, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/github/actions/get_contents.py", line 15, in run
    result = contents_to_dict(contents=contents, decode=decode)
  File "/opt/stackstorm/packs/github/actions/lib/formatters.py", line 212, in contents_to_dict
    content = decode_base64(content)
  File "/opt/stackstorm/packs/github/actions/lib/formatters.py", line 240, in decode_base64
    data += b'=' * (4 - missing_padding)
TypeError: can only concatenate str (not "bytes") to str
"
  stdout: ''
```

And here is my ST2 environment that I ran those actions.
```
ubuntu@localhost:~$ st2 --version
st2 3.5.0, on Python 3.8.5
ubuntu@localhost:~$ st2 pack get github
+-------------+--------------------------+
| Property    | Value                    |
+-------------+--------------------------+
| name        | github                   |
| version     | 2.0.1                    |
| author      | StackStorm, Inc.         |
| email       | info@stackstorm.com      |
| keywords    | [                        |
|             |     "github",            |
|             |     "github enterprise", |
|             |     "git",               |
|             |     "scm",               |
|             |     "serverless"         |
|             | ]                        |
| description | GitHub integration       |
+-------------+--------------------------+
ubuntu@localhost:~$ 
```

**Comment by userlocalhost** [comment]
Another similar problem was happened in action `github.create_file`. This execution would be okey.
```
$ st2 run github.create_file repo='test-repo-2021-0719-01' user='userlocalhost' \
> message='test of github_create_file action' content='hoge' path='test01'
```

But following one which adds `encoding` parameter must be failed at the same point of initial report.
```
$ st2 run github.create_file repo='test-repo-2021-0719-01' user='userlocalhost' \
> message='test of github_create_file action' content='hoge' path='test02' encoding=base64
```

This is an execution result of this action.
```
ubuntu@localhost:~$ st2 run github.create_file repo='test-repo-2021-0719-01' user='userlocalhost' message='test of github_create_file action' content='hoge02' path='test02' encoding=base64
.                                                                                                                                                                                                                                                                                                                             
id: 60f4db93b89e28c755292352                                                                                                                                                                                                                                                                                                  
action.ref: github.create_file                                                                                                                                                                                                                                                                                                
context.user: st2admin                                                                                                                                                                                                                                                                                                        
parameters:                                                                                                                                                                                                                                                                                                                   
  content: hoge02                                                                                                                                                                                                                                                                                                             
  encoding: base64                                                                                                                                                                                                                                                                                                            
  message: test of github_create_file action                                                                                                                                                                                                                                                                                  
  path: test02                                                                                                                                                                                                                                                                                                                
  repo: test-repo-2021-0719-01                                                                                                                                                                                                                                                                                                
  user: userlocalhost                                                                                                                                                                                                                                                                                                         
status: failed                                                                                                                                                                                                                                                                                                                
start_timestamp: Mon, 19 Jul 2021 01:55:31 UTC                                                                                                                                                                                                                                                                                
end_timestamp: Mon, 19 Jul 2021 01:55:32 UTC                                                                                                                                                                                                                                                                                  
result:                                                                                                                                                                                                                                                                                                                       
  exit_code: 1                                                                                                                                                                                                                                                                                                                
  result: None                                                                                                                                                                                                                                                                                                                
  stderr: "Traceback (most recent call last):                                                                                                                                                                                                                                                                                 
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 395, in <module>                                                                                                                                                                                                        
    obj.run()                                                                                                                                                                                                                                                                                                                 
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 214, in run                                                                                                                                                                                                             
    output = action.run(**self._parameters)                                                                                                                                                                                                                                                                                   
  File "/opt/stackstorm/packs/github/actions/create_file.py", line 16, in run                                                                                                                                                                                                                                                 
    content = decode_base64(content)                                                                                                                                                                                                                                                                                          
  File "/opt/stackstorm/packs/github/actions/lib/formatters.py", line 240, in decode_base64                                                                                                                                                                                                                                   
    data += b'=' * (4 - missing_padding)                                                                                                                                                                                                                                                                                      
TypeError: can only concatenate str (not "bytes") to str                                                                                                                                                                                                                                                                      
"                                                                                                                                                                                                                                                                                                                             
  stdout: ''
```

Something is wrong with `decode_base64`. It should be fixed.
